web-app/rideshareapp/urls.py
from django.urls import path

from . import views

app_name = 'rideshareapp'
urlpatterns = [
    path('index', views.index, name= 'index'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('signup/', views.signup, name = 'signup'),
    path('request_ride/', views.request_ride, name = 'request_ride'),
    path('join_share/<int:ride_id>/<int:sharer_num>', views.join_share, name = 'join_share'),
    path('take_order/<int:ride_id>/', views.take_order, name = 'take_order'),
    path('request_share/', views.request_share, name = 'request_share'),
    path('find_order/', views.find_order, name = 'find_order'),
    path('register_driver/', views.register_driver, name = 'register_driver'),
    path('edit_vehicle/', views.edit_vehicle, name = 'edit_vehicle'),
    path('super_ride/', views.super_ride, name = 'super_ride'),
    path('find_open/', views.find_open, name = 'find_open'),
    path('edit_open/<int:ride_id>', views.edit_open, name = 'edit_open'),
    path('cancel_order/<int:ride_id>', views.cancel_order, name = 'cancel_order'),
    path('find_confirmed/', views.find_confirmed, name = 'find_confirmed'),
    path('view_ride/<int:ride_id>', views.view_ride, name = 'view_ride'),
    path('finish_ride/<int:ride_id>', views.finish_ride, name = 'finish_ride'),
    path('view_personal/', views.view_personal, name = 'view_personal'),
    path('edit_useraccount/', views.edit_useraccount, name = 'edit_useraccount'),
    path('delete_driver/', views.delete_driver, name = 'delete_driver'),
]

web-app/rideshareproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("rideshareapp/", include('rideshareapp.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]

web-app/rideshareapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField

# Create your models here.
class Userinfo(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    user_name = models.CharField(max_length=200)
    driver_status = models.BooleanField()
    type = models.CharField(max_length=200, null=True)
    plate = models.CharField(max_length=200, null=True)
    passengers_num = models.IntegerField(null=True)
    special_vehicle_info = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.user_name

class Ride(models.Model):
    user = models.ForeignKey(Userinfo, on_delete=models.CASCADE)
    owner_name = models.CharField(max_length=200)
    destination = models.CharField(max_length=200)
    arrival_time = models.DateTimeField('Arrival date & time')
    shared_status = models.BooleanField(default=False)
    owner_num = models.IntegerField()
    passenger_num = models.IntegerField()

    sharer_num = ArrayField(ArrayField(models.IntegerField()), default=[])
    sharer_name = ArrayField(models.CharField(max_length=200), default=[])
    
    ride_status = models.CharField(max_length=200, default='open')
    driver_name = models.CharField(max_length=200, null=True, blank=True)
    vehicle_type = models.CharField(max_length=200, blank=True)
    special_request = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.owner_name

web-app/rideshareapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Ride
from django.core.validators import MinValueValidator
from django.contrib.auth import authenticate


class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)


class SignupForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    firstname = forms.CharField(label='First name', max_length=100, required=False)
    lastname = forms.CharField(label='Last name', max_length=100, required=False)
    email = forms.EmailField(label='Email Address', required=False)

class EditUserInfoForm(forms.Form):
    firstname = forms.CharField(label='First name', max_length=100, required=False)
    lastname = forms.CharField(label='Last name', max_length=100, required=False)
    email = forms.EmailField(label='Email Address', required=False)

class RequestRideForm(forms.Form):
    destination = forms.CharField(label='destination', max_length=100)
    arrival_time = forms.DateTimeField(label='Arrival Time(format: yyyy-mm-dd 00:00)')
    owner_num = forms.IntegerField(label='Number of passengers')
    shared_status = forms.BooleanField(label='Shared or Not', required=False)
    vehicle_type = forms.CharField(label='Vehicle Type', max_length=100, required=False)
    special_request = forms.CharField(label='Special Request', max_length=100, required=False)

    def clean_owner_num(self):
        owner_num = self.cleaned_data.get('owner_num')

        if owner_num <= 0:
            raise forms.ValidationError("You can not set non-positive owner number!")
        return owner_num

class RequestShareForm(forms.Form):
    arrival_from = forms.DateTimeField(label='Arrival Time From(format: yyyy-mm-dd 00:00)')
    arrival_to = forms.DateTimeField(label='Arrival Time To(format: yyyy-mm-dd 00:00)')
    destination = forms.CharField(label='Destination address', max_length=100)
    sharer_num = forms.IntegerField(label='Number of sharers')

    def clean_sharer_num(self):
        sharer_num = self.cleaned_data.get('sharer_num')
        if sharer_num <= 0:
            raise forms.ValidationError("You can not set non-positive sharer number!")
        return sharer_num

class RegisterVehicleForm(forms.Form):
    plate = forms.CharField(label='plate', max_length=100)
    type = forms.CharField(label='type', max_length=100)
    special_vehicle_info = forms.CharField(label='special_vehicle_info', max_length=100, required=False)
    passengers_num = forms.IntegerField(label='passengers_num')

class EditOpenRideFormOwner(forms.Form):
    destination = forms.CharField(label='destination', max_length=100)
    arrival_time = forms.DateTimeField(label='Arrival Time(format: yyyy-mm-dd 00:00)')
    owner_num = forms.IntegerField(label='Number of passengers')
    shared_status = forms.BooleanField(label='Shared or Not', required=False)
    vehicle_type = forms.CharField(label='Vehicle Type', max_length=100, required=False)
    special_request = forms.CharField(label='Special Request', max_length=100, required=False)

    def clean_owner_num(self):
        owner_num = self.cleaned_data.get('owner_num')

        if owner_num <= 0:
            raise forms.ValidationError("You can not set non-positive owner number!")
        return owner_num

class EditOpenRideFormSharer(forms.Form):
    sharer_num = forms.IntegerField(label='Number of sharers', validators=[MinValueValidator(1)])

    def clean_sharer_num(self):
        sharer_num = self.cleaned_data.get('sharer_num')

        if sharer_num <= 0:
            raise forms.ValidationError("You can not set non-positive sharer number!")
        return sharer_num

web-app/rideshareapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.contrib.auth import authenticate
from .forms import LoginForm, SignupForm, RequestRideForm, RequestShareForm, RegisterVehicleForm, EditOpenRideFormOwner, EditOpenRideFormSharer, EditUserInfoForm
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.core.mail import send_mail
from .models import Userinfo, Ride
from django.db.models import Q


# Create your views here.

@login_required
def index(request):
    user = request.user
    userinfo = get_object_or_404(Userinfo, user=user)
    
    return render(request, 'rideshareapp/index.html', {'userinfo': userinfo})

@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('rideshareapp:login'))

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            # check username and password are valid
            user = authenticate(username = username, password = password)
            if user is not None:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('rideshareapp:index'))
            else:
                error_msg = "User or password is not correct"
                return render(request, 'rideshareapp/login.html', {'form': form, 'error_msg': error_msg})
        else:
            return render(request, 'rideshareapp/login.html', {'form': form})
    else:
        form = LoginForm()
    return render(request, 'rideshareapp/login.html', {'form': form})

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            firstname = form.cleaned_data.get('firstname')
            lastname = form.cleaned_data.get('lastname')
            email = form.cleaned_data.get('email')
            user = User.objects.create_user(username=username, password=password, first_name=firstname, last_name=lastname, email=email)
            Userinfo.objects.create(user=user, user_name=user.username, driver_status=False)
            return HttpResponseRedirect(reverse('rideshareapp:login'))
    else:
        form = SignupForm()
    return render(request, 'rideshareapp/signup.html', {'form': form})


@login_required
def request_ride(request):
    user = request.user
    userinfo = get_object_or_404(Userinfo, user=user)
    if request.method == 'POST':
        form = RequestRideForm(request.POST)
        if form.is_valid():
            destination = form.cleaned_data.get('destination')
            arrival_time = form.cleaned_data.get('arrival_time')
            owner_num = form.cleaned_data.get('owner_num')
            shared_status = form.cleaned_data.get('shared_status')
            vehicle_type = form.cleaned_data.get('vehicle_type')
            special_request = form.cleaned_data.get('special_request')
            Ride.objects.create(user = userinfo, owner_name = userinfo.user_name, destination = destination, arrival_time = arrival_time, owner_num = owner_num, 
                shared_status = shared_status, vehicle_type = vehicle_type, special_request = special_request, passenger_num = owner_num)

            return HttpResponseRedirect(reverse('rideshareapp:index'))
            
    else:
        form = RequestRideForm()
    return render(request, 'rideshareapp/request_ride.html', {'form': form})

@login_required
def edit_vehicle(request):
    user = request.user
    userinfo = get_object_or_404(Userinfo, user=user)
    if request.method == 'POST':
        form = RegisterVehicleForm(request.POST)
        if form.is_valid():
            type = form.cleaned_data.get('type')
            plate = form.cleaned_data.get('plate')
            special_vehicle_info =form.cleaned_data.get('special_vehicle_info')
            passengers_num = form.cleaned_data.get('passengers_num')
            userinfo.type = type
            userinfo.plate = plate
            userinfo.special_vehicle_info = special_vehicle_info
            userinfo.passengers_num = passengers_num
            userinfo.driver_status = True
            userinfo.save()
            return HttpResponseRedirect(reverse('rideshareapp:index'))
    else:
        form = RegisterVehicleForm()
        if userinfo.driver_status:
            form.fields["plate"].initial = userinfo.plate
            form.fields["type"].initial = userinfo.type
            form.fields["special_vehicle_info"].initial = userinfo.special_vehicle_info
            form.fields["passengers_num"].initial = userinfo.passengers_num

        
    return render(request, 'rideshareapp/edit_vehicle.html', {'form': form})

@login_required
def find_order(request):
    user = request.user
    userinfo = get_object_or_404(Userinfo, user=user)
    type = userinfo.type
    vehicle_capacity = userinfo.passengers_num  
    ride_typ_filled = Ride.objects.filter(ride_status='open', passenger_num__lte = vehicle_capacity, vehicle_type=type)
    ride_typ_null = Ride.objects.filter(ride_status='open', passenger_num__lte = vehicle_capacity, vehicle_type='')
    ride_all = ride_typ_filled|ride_typ_null
    result_ride = []
    for each_ride in list(ride_all):
        if each_ride.owner_name != userinfo.user_name and userinfo.user_name not in each_ride.sharer_name:
            result_ride.append(each_ride)
    return render(request, 'rideshareapp/find_order.html', {'result_ride': result_ride})

@login_required
def take_order(request, ride_id):
    user = request.user
    userinfo = get_object_or_404(Userinfo, user=user)
    ride = get_object_or_404(Ride, id = ride_id)
    ownerName = ride.owner_name
    sharerName = ride.sharer_name
    email_list = []
    ownerEmail = get_object_or_404(User, username = ownerName).email
    if ownerEmail:
        email_list.append(ownerEmail)
    for sharer in sharerName:
        sharerEmail = get_object_or_404(User, username = sharer).email
        if sharerEmail:
            email_list.append(sharerEmail)
    
    if request.method == 'POST':
        # print(email_list)
        send_mail(
            'RideShare Order Confirmed',
            'Your order is confirmed by a driver',
            'rideshareyz@outlook.com',
            email_list,
            fail_silently=False,
        )
        ride.ride_status = 'confirmed'
        ride.driver_name = userinfo.user_name
        ride.vehicle_type = userinfo.type 
        ride.save()
        
        return HttpResponseRedirect(reverse('rideshareapp:index'))
    return render(request, 'rideshareapp/take_order.html', {'ride': ride})


@login_required
def register_driver(request):
    user = request.user
    userinfo = get_object_or_404(Userinfo, user=user)
    if request.method == 'POST':
        form = RegisterVehicleForm(request.POST)
        if form.is_valid():
            type = form.cleaned_data.get('type')
            plate = form.cleaned_data.get('plate')
            special_vehicle_info =form.cleaned_data.get('special_vehicle_info')
            passengers_num = form.cleaned_data.get('passengers_num')
            userinfo.type = type
            userinfo.plate = plate
            userinfo.special_vehicle_info = special_vehicle_info
            userinfo.passengers_num = passengers_num
            userinfo.driver_status = True
            userinfo.save()
            return HttpResponseRedirect(reverse('rideshareapp:index'))
    else:
        form = RegisterVehicleForm()
    return render(request, 'rideshareapp/register_driver.html', {'form': form})
            




@login_required
def request_share(request):
    user = request.user
    userinfo = get_object_or_404(Userinfo, user=user)
    if request.method == 'POST':
        form = RequestShareForm(request.POST)
        if form.is_valid():
            arrival_from = form.cleaned_data.get('arrival_from')
            arrival_to = form.cleaned_data.get('arrival_to')
            destination = form.cleaned_data.get('destination')
            sharer_num = form.cleaned_data.get('sharer_num')
            ride_all = Ride.objects.filter(destination = destination, arrival_time__range=[arrival_from, arrival_to], ride_status='open', shared_status = True)
            
            result_ride = []
            for each_ride in list(ride_all):
                if userinfo.user_name not in each_ride.sharer_name and userinfo.user_name != each_ride.owner_name:
                    result_ride.append(each_ride)


            return render(request, 'rideshareapp/find_share.html', {'result_ride': result_ride, 'sharer_num': sharer_num})
            
    else:
        form = RequestShareForm()
    return render(request, 'rideshareapp/request_share.html', {'form': form})


@login_required
def join_share(request, ride_id, sharer_num):
    user = request.user
    userinfo = get_object_or_404(Userinfo, user=user)
    ride = get_object_or_404(Ride, id = ride_id)
    if request.method == 'POST':
        # update ride
        ride.sharer_num.append([user.id, sharer_num])
        ride.sharer_name.append(userinfo.user_name)
        ride.passenger_num = ride.passenger_num + sharer_num
        ride.save()
        return HttpResponseRedirect(reverse('rideshareapp:index'))
    return render(request, 'rideshareapp/join_share.html', {'ride': ride, 'sharer_num': sharer_num})


@login_required
def find_open(request):
    user = request.user
    userinfo = get_object_or_404(Userinfo, user=user)
    sharer_list = []
    sharer_list.append(userinfo.user_name)
    sharer_ride = Ride.objects.filter(ride_status='open', sharer_name__contains=sharer_list)

web-app/rideshareapp/templates/rideshareapp/index.html
<!DOCTYPE html>
<html lang="en">

<!-- Basic Page Needs––––––––––––––––––––––––––– -->

<head>
    <meta http-equiv="content-type" content="text/html">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--SEO meta tags-->
    <!--    Change the index to your website's name-->
    <title>RideShare Webapp</title>
    <!-- Bootstrap Core CSS ––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous" />
    <!-- fontawesome ––––––––––––––––––––––––––– -->
    <script src="https://kit.fontawesome.com/5c9f2dfb26.js"></script>
    <!-- To add a google font and paste the link -->
    <style>
    html {
        /*    1rem = 16px*/
        font-size: 1rem;
    }
    
    body {
        background-color: white;
        font-family: 'Futura', sans-serif;
        line-height: 1.5;
    }
    
    p {
        margin-bottom: 1.3rem;
    }
    
    /*this is a group selection, selecting all the headlines h1-h4*/
    h1,
    h2,
    h3,
    h4 {
        /*    headline font*/
        font-family: 'Merriweather Sans', sans-serif;
        font-weight: 700;
        line-height: 1.2;
    }
    
    h1 {
        /*  top:0 right:0  bottom:0.5rem left:0*/
        margin: 0 0 0.5rem 0;
        font-size: 3.157rem;
    }
    
    h2 {
        /*  top:1.414rem right:0  bottom:0.5rem left:0*/
        margin: 1.414rem 0 0.5rem 0;
        font-size: 2.369rem;
    }
    
    h3 {
        /*  top:1.414rem right:0  bottom:0.5rem left:0*/
        margin: 1.414em 0 0.5rem 0;
        font-size: 1.777rem;
    }
    
    h4 {
        /*  top:1.414rem right:0  bottom:0.5rem left:0*/
        margin: 1.414em 0 0.5rem 0;
        font-size: 1.333rem;
    }
    
    
    /*Interactive elements*/
    /* link*/
    a {
        color:#166088;
    }
    
    a:hover {
        /* color: #C0D6DF; */
        color: orange;
        text-decoration: none;
    }
    
    /*self-defined class names*/
    .view {
        background:rgb(220,188,248)  center center no-repeat;
        background-size: cover;
        padding-top: 11rem;
        padding-bottom: 3.5rem;
    }
    
    .view h1{
        padding-left:50px;
        color: orange;
    }
    
    
    .projectbackground{
        /* background-color:#F2C299; */
        background-color:rgb(228, 242, 247);
        padding-top: 6.5rem;
        padding-bottom: 5rem;
    }
    
    .project img {
        filter: grayscale(50%);
    }
    
    .project img:hover {
        filter: grayscale(0%);
    }
    
    /*navigation*/
    /*-----navigation background------*/
    .navbackground{
        background-color:rgb(255,255,255,0.7);
    }
    
    /*-----navigation button in the mobile view------*/
    /*-----navigation brand name------*/
    .navbar-light .navbar-brand {
        padding-left: 1rem;
        color: #996666;
        font-weight:900;
    }
    
    /*-----navigation brand name hover color----*/
    .navbar-light .navbar-brand:hover{
        color: #166088;
    }
    
    /*-------navigation menu links--------*/
    .navbar-light .navbar-nav .nav-link{
        color: #4F6D7A;
        font-size:1.2rem;
        padding-right: 1rem;
    }
    
    .navbar-light .navbar-nav :hover{
        color: orange;
    }
    
    .contactbackground {
        padding-top: 1rem;
        background-color: #C0D6DF;
        color: #4F6D7A;
    }
    
    /*footer*/
    footer{
        padding-top: 2rem;
        padding-bottom: 2rem;
    }
    
    .info{
        margin-top: 2rem;
        margin-bottom: 2rem;
    }
    
    .contactbackground p{
        margin-top: 0.5rem;
        font-size: 1.2rem;
    }
    
    .date{
        margin-top: 5rem;
    }
    
    </style>
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="100">

    <nav class="navbar  navbar-light navbar-expand-sm navbackground fixed-top">

        <!--     add d-block d-sm-none class name if you just want the brand name to appear in the mobile view.-->
        <a class="navbar-brand page-scroll">RideShare Webapp</a>
        <!--        Try justify-content-start, justify-content-end or justify-content-between, justify-content-around to see different layout styles for the navigation.-->
        <div class="collapse navbar-collapse  justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <span class="nav-link page-scroll">Hi, {{userinfo.user_name}} <a href = "{% url 'rideshareapp:logout' %}">Logout</a></span>
                </li>
    
            </ul>
        </div>
    </nav>

    <!--    main content starts from here. Use container or container-fluid-->
    <div class="container-fluid view" id='view'>
        <div class='row justify-content-start align-items-center'>
            <div class='col-sm-5 text-center'>
                <h1>RideShare Webapp</h1>
            </div>
        </div>
    </div>

    <div class = 'projectbackground'  id='portfolio'>
        <div class="container project">
            <div class='row justify-content-center align-items-center'>
                <div class='col-sm-4 text-center'>
                    <!-- <a href = "{% url 'rideshareapp:view_personal' %}" ><img class='img-fluid' src='/img/login.jpg' alt='portfolio' width='200' height='200'></a> -->
                    <h3><a href = "{% url 'rideshareapp:view_personal' %}" style="text-decoration: none"> Portfolio </a></h3>
                </div>
                <div class='col-sm-4 text-center'>
                    <!-- <a href = "/portfolio/" ><img class='img-fluid' src='../static/img/portfolio.png' alt='project1pic' width='200' height='200'></a> -->
                    <h3><a href = "{% url 'rideshareapp:request_ride' %}" style="text-decoration: none"> Request Ride </a></h3>
                </div>
                <div class='col-sm-4 text-center'>
                    <!-- <a href = "/portfolio/" ><img class='img-fluid' src='../static/img/portfolio.png' alt='project1pic' width='200' height='200'></a> -->
                    <h3><a href = "{% url 'rideshareapp:request_share' %}"style="text-decoration: none"> Request Share </a></h3>
                </div>
                <div class='col-sm-4 text-center'>
                    <!-- <a href = "/portfolio/" ><img class='img-fluid' src='../static/img/portfolio.png' alt='project1pic' width='200' height='200'></a> -->
                    <h3><a href = "{% url 'rideshareapp:find_open' %}" style="text-decoration: none"> Open ride </a></h3>
                </div>

                <div class='col-sm-4 text-center'>
                    <!-- <a href = "/portfolio/" ><img class='img-fluid' src='../static/img/portfolio.png' alt='project1pic' width='200' height='200'></a> -->
                    <h3><a href = "{% url 'rideshareapp:super_ride' %}"style="text-decoration: none"> Non-complete ride </a></h3>
                </div>
                <div class='col-sm-4 text-center'>
                    <!-- <a href = "/portfolio/" ><img class='img-fluid' src='../static/img/portfolio.png' alt='project1pic' width='200' height='200'></a> -->
                    <h3><a href = "{% url 'rideshareapp:find_confirmed' %}"style="text-decoration: none"> Confirmed ride </a></h3>
                </div>
                {% if userinfo.driver_status %}
                    <div class='col-sm-4 text-center'>
                        <!-- <a href = "/portfolio/" ><img class='img-fluid' src='../static/img/portfolio.png' alt='project1pic' width='200' height='200'></a> -->
                        <h3><a href = "{% url 'rideshareapp:edit_vehicle' %}"style="text-decoration: none"> Edit driver info </a></h3>
                    </div>
                    <div class='col-sm-4 text-center'>
                        <!-- <a href = "/portfolio/" ><img class='img-fluid' src='../static/img/portfolio.png' alt='project1pic' width='200' height='200'></a> -->
                        <h3><a href = "{% url 'rideshareapp:find_order' %}"style="text-decoration: none"> Find order </a></h3>
                    </div>

                {% else %}
                    <div class='col-sm-4 text-center'>
                        <!-- <a href = "/portfolio/" ><img class='img-fluid' src='../static/img/portfolio.png' alt='project1pic' width='200' height='200'></a> -->
                        <h3><a href = "{% url 'rideshareapp:register_driver' %}"style="text-decoration: none"> Register driver info </a></h3>
                    </div>
                {% endif %}

            </div>
        </div>
    </div>


    <div class='contactbackground' id='contact'>
        <footer class='container text-center'>
            <h2>I would love to hear from you!</h2>
            <p>If you have any questions, please let us know.</p>
        
            <div class='info'>
                <p><a href='mailto:yikai.liu@duke.edu'>yikai.liu@duke.edu</a></p>
                <p><a href='mailto:zuhang.xu@duke.edu'>zuhang.xu@duke.edu</a></p>
            </div>

        </footer>
    </div>






    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js "></script>
</body>

</html>

























<!-- <!DOCTYPE html>
<html>
    <body>
        <h1> Hello, {{userinfo.user_name}}</h1>
        <button type="button"> <a href = "{% url 'rideshareapp:view_personal' %}"> View your personal info </a> </button><br>
        <button type="button"> <a href = "{% url 'rideshareapp:request_ride' %}"> Request Ride </a> </button><br>
        <button type="button"> <a href = "{% url 'rideshareapp:request_share' %}"> Request Share </a></button><br>
        <button type="button"> <a href = "{% url 'rideshareapp:find_open' %}"> Find your open ride </a></button><br>
        <button type="button"> <a href = "{% url 'rideshareapp:find_confirmed' %}"> Find your confirmed ride </a></button><br>
        <button type="button"> <a href = "{% url 'rideshareapp:super_ride' %}"> All your ride! </a></button><br>
        <button type="button"> <a href = "{% url 'rideshareapp:logout' %}"> Log Out! </a></button><br>

        {% if userinfo.driver_status %}

            <button type="button"> <a href = "{% url 'rideshareapp:edit_vehicle' %}"> Edit your driver info! </a> </button><br>
            <button type="button"> <a href = "{% url 'rideshareapp:find_order' %}"> Find order! </a></button><br>

        {% else %}
            <button type="button"> <a href = "{% url 'rideshareapp:register_driver' %}"> Register your driver info! </a> </button><br>
        {% endif %}

        
    </body>

</html>  -->